version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8081:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15-bullseye
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/  # This volume will persist data

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - ./nginx/certbot:/var/www/certbot
      - .:/app
    depends_on:
      web:
        condition: service_started
      certbot:
        condition: service_healthy
  
  certbot:
    image: certbot/certbot
    container_name: certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email fahrultech@gmail.com --agree-tos --no-eff-email -d refactoringdaily.com --rsa-key-size 2048
    volumes:
      - certbot-etc:/etc/letsencrypt
      - ./nginx/certbot:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    healthcheck:
      test: ["CMD-SHELL", "test -f /etc/letsencrypt/live/refactoringdaily.com/fullchain.pem && test -f /etc/letsencrypt/live/refactoringdaily.com/privkey.pem"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
  certbot-etc:
    driver: local
  certbot-var: