# Generated by Django 4.2.16 on 2024-09-10 21:27

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('featured_position', models.PositiveSmallIntegerField(choices=[(0, 'Not Featured'), (1, 'Feature 1'), (2, 'Feature 2'), (3, 'Feature 3'), (4, 'Feature 4'), (5, 'Feature 5')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
