# Generated by Django 4.2.16 on 2024-09-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
    ]
